### ISSUE TITLE
Resolved: Select * from movie not working

### ISSUE THREAD

**Issue by pma2** [LDSSA/batch2-BLU05#3]
I am using an alternate DB browser: https://www.etl-tools.com/database-browser/overview.html
I can see the tables and contents, for example, from oscar table:
![image](https://user-images.githubusercontent.com/38791092/41204676-b0f58b60-6cdf-11e8-9ded-32aee3dcdcf0.png)
But movie table is empty...

*Correction* if I run
```
select * from blu05.movie limit 1
```
Works. But some records have apparently a character that outputs an error, that comes up when reading with limit 100, for example:
"character with byte sequence 0xe6 0x91 0x87 in encoding "UTF8" has no equivalent in encoding "WIN1252""

Any clue?
Thanks

**Comment by pma2** [comment]
Seems related to this:
https://stackoverflow.com/questions/42130110/character-with-byte-sequence-0x9d-in-encoding-win1252-has-no-equivalent-in-enc

**Comment by pma2** [comment]
I can read it with pd.read_sql_query. The problem seems to be id = 30, that has Chinese or other similar chars...

**Comment by dominguezmaria** [comment]
The problem seems to be that the SQL client is trying to read the database data using the WIN1252 (encoding instead of UTF-8), while WIN1252 doesn't know how to handle Chinese characters.
You can check in the client's preferences if there is an option to select a different encoding.
If that doesn't work, or it seems too much time consuming, go ahead and do it all with pandas 🐼!

**Comment by pma2** [comment]
Works on Pandas :)
